# Generated by Django 5.2.1 on 2026-03-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.ImageField(upload_to='orders/references/')),
                ('custom_fabric_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.fabric')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instruction_image', models.ImageField(upload_to='measurements/instructions/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='ecommerce.customorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.measurementpart')),
            ],
        ),
        migrations.CreateModel(
            name='NeckDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='designs/necks/')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='designs/sleeves/')),
            ],
        ),
        migrations.CreateModel(
            name='StandardSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StandardSizeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Default value in inches')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.measurementpart')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='ecommerce.standardsize')),
            ],
            options={
                'unique_together': {('size', 'part')},
            },
        ),
        migrations.RemoveField(
            model_name='custommeasurement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='VirtualTryOn',
        ),
        migrations.AddField(
            model_name='customorder',
            name='neck_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.neckdesign'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sleeve_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.sleevetype'),
        ),
        migrations.DeleteModel(
            name='CustomMeasurement',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
