# Generated by Django 5.2.1 on 2026-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_customorder_measurementpart_measurementvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='7356198300', max_length=20)),
                ('business_email', models.EmailField(default='contact@casaamora.com', max_length=254)),
                ('default_country_code', models.CharField(default='+91', max_length=5)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='clientdiary',
            options={'verbose_name_plural': 'Client Diaries'},
        ),
        migrations.AlterModelOptions(
            name='spotlight',
            options={'ordering': ['order'], 'verbose_name_plural': 'Spotlights'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='is_read',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('urgent', 'Urgent'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('fabric_selection', 'Fabric Selection'), ('stitching', 'Stitching'), ('shipped', 'Shipped'), ('finished', 'Finished'), ('payment_pending', 'Payment Pending')], default='received', max_length=20),
        ),
    ]
