# Generated by Django 5.2.1 on 2026-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_globalconfiguration_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('new_enquiry', 'New Enquiry 🔔'), ('received', 'Received'), ('fabric_selection', 'Fabric Selection'), ('stitching', 'Stitching'), ('shipped', 'Shipped'), ('finished', 'Finished'), ('payment_pending', 'Payment Pending')], default='new_enquiry', max_length=20),
        ),
    ]
