# Generated by Django 5.2.1 on 2026-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_inquiry_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
