# Generated by Django 5.2.1 on 2026-03-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_globalconfiguration_options_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='active_theme',
            field=models.CharField(choices=[('atelier', 'Modern Atelier (Monochrome)'), ('wine_red', 'Wine Red Editorial')], default='wine_red', max_length=20),
        ),
    ]
