# Generated by Django 5.2.1 on 2026-03-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_globalconfiguration_active_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(blank=True, help_text="User's uploaded photo", null=True, upload_to='orders/references/')),
                ('ai_tryon_result', models.ImageField(blank=True, null=True, upload_to='orders/tryon/')),
                ('custom_fabric_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('New', 'New Enquiry 🔔'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching'), ('Finished', 'Finished'), ('Ready', 'Ready for Pickup')], default='New', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.fabric')),
                ('neck_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.neckdesign')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('sleeve_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.sleevetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='7356198300', max_length=20)),
                ('business_email', models.EmailField(default='contact@casaamora.com', max_length=254)),
                ('default_country_code', models.CharField(default='+91', max_length=5)),
                ('theme_mode', models.CharField(choices=[('monochrome', 'Modern Atelier (Monochrome)'), ('wine_red', 'Wine Red Editorial')], default='wine_red', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='neck_design',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='sleeve_type',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measurementvalue',
            name='custom_order',
        ),
        migrations.DeleteModel(
            name='GlobalConfiguration',
        ),
        migrations.AddField(
            model_name='measurementvalue',
            name='bespoke_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='ecommerce.bespokeorder'),
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
