# Generated by Django 5.2.1 on 2026-03-31 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_bespokeorder_siteconfig_remove_customorder_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Order Received'), ('In-Stitching', 'In-Stitching 🧵'), ('Ready', 'Ready for Delivery'), ('Shipped', 'Shipped ✈️'), ('Delivered', 'Delivered ✅')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI / Google Pay'), ('COD', 'Cash on Delivery')], default='UPI', max_length=10)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('stitching_notes', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
