# Generated by Django 5.2.1 on 2026-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_product_is_out_of_stock_product_stock_level_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, default='Casa Amora Atelier, Kozhikode, Kerala, India'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='display_phone',
            field=models.CharField(blank=True, default='+91 73561 98300', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/casaamora'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/casaamora'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
