# Generated by Django 5.2.1 on 2026-04-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_siteconfig_address_siteconfig_display_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bespokeorder',
            options={'verbose_name': 'Custom Creation', 'verbose_name_plural': 'Custom Creations'},
        ),
        migrations.AlterModelOptions(
            name='clientdiary',
            options={'verbose_name': 'Client Diary', 'verbose_name_plural': 'Client Diaries'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Special Inquiry', 'verbose_name_plural': 'Special Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Atelier Configuration', 'verbose_name_plural': 'Atelier Configuration'},
        ),
        migrations.AlterModelOptions(
            name='spotlight',
            options={'ordering': ['order'], 'verbose_name': 'Home Spotlight', 'verbose_name_plural': 'Home Spotlights'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Client Story', 'verbose_name_plural': 'Client Stories'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Registry Wishlist', 'verbose_name_plural': 'Registry Wishlists'},
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='ai_tryon_result',
        ),
    ]
