# Generated by Django 5.2.1 on 2026-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_bespokeorder_options_alter_clientdiary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bespokeorder',
            options={'verbose_name': 'Customize on Your Style Order', 'verbose_name_plural': 'Customize on Your Style Orders'},
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'New Enquiry 🔔'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching 🧵'), ('Finishing', 'Finishing'), ('Ready', 'Ready for Pickup'), ('Shipped', 'Shipped ✈️'), ('Delivered', 'Delivered ✅')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Received'), ('Cutting', 'Cutting'), ('Stitching', 'Stitching 🧵'), ('Finishing', 'Finishing'), ('Ready', 'Ready for Delivery'), ('Shipped', 'Shipped ✈️'), ('Delivered', 'Delivered ✅')], default='Pending', max_length=20),
        ),
    ]
