# Generated by Django 5.2.1 on 2026-04-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_bespokeorder_options_bespokeorder_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='campaigns/desktop/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='campaigns/mobile/')),
                ('video_url', models.URLField(blank=True, help_text='Optional background video URL', null=True)),
                ('cta_text', models.CharField(default='Discover', max_length=50)),
                ('cta_link', models.CharField(default='/shop', max_length=200)),
                ('text_light', models.BooleanField(default=True, help_text='Check if text should be light (for dark backgrounds)')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero Campaign',
                'verbose_name_plural': 'Hero Campaigns',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Spotlight',
        ),
    ]
